// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RVCoreBoard.MVC.DataContext;

namespace RVCoreBoard.MVC.Migrations
{
    [DbContext(typeof(RVCoreBoardDBContext))]
    partial class RVCoreBoardDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RVCoreBoard.MVC.Models.Attach", b =>
                {
                    b.Property<int>("ANo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BNo");

                    b.Property<string>("FileFullName")
                        .IsRequired();

                    b.Property<int>("FileSize");

                    b.Property<DateTime>("Reg_Date");

                    b.HasKey("ANo");

                    b.HasIndex("BNo");

                    b.ToTable("Attachs");
                });

            modelBuilder.Entity("RVCoreBoard.MVC.Models.Board", b =>
                {
                    b.Property<int>("BNo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cnt_Read");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<int?>("DataBNo");

                    b.Property<DateTime>("Reg_Date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<int>("UNo");

                    b.HasKey("BNo");

                    b.HasIndex("DataBNo");

                    b.HasIndex("UNo");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("RVCoreBoard.MVC.Models.Comment", b =>
                {
                    b.Property<int>("CNo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BNo");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<DateTime>("Reg_Date");

                    b.Property<int>("UNo");

                    b.HasKey("CNo");

                    b.HasIndex("BNo");

                    b.HasIndex("UNo");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("RVCoreBoard.MVC.Models.User", b =>
                {
                    b.Property<int>("UNo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(300);

                    b.Property<DateTime>("Birth");

                    b.Property<string>("DetailAddress")
                        .HasMaxLength(300);

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Tel")
                        .HasMaxLength(20);

                    b.HasKey("UNo");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RVCoreBoard.MVC.Models.Attach", b =>
                {
                    b.HasOne("RVCoreBoard.MVC.Models.Board", "board")
                        .WithMany()
                        .HasForeignKey("BNo")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RVCoreBoard.MVC.Models.Board", b =>
                {
                    b.HasOne("RVCoreBoard.MVC.Models.Board", "Data")
                        .WithMany()
                        .HasForeignKey("DataBNo");

                    b.HasOne("RVCoreBoard.MVC.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UNo")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RVCoreBoard.MVC.Models.Comment", b =>
                {
                    b.HasOne("RVCoreBoard.MVC.Models.Board", "board")
                        .WithMany()
                        .HasForeignKey("BNo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RVCoreBoard.MVC.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UNo")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
